"""
Compliance Report Pydantic Model

Defines the structure for audit reports generated by the Wargame Runner.
"""

from datetime import datetime, timezone
from typing import List, Dict, Optional, Literal
from pydantic import BaseModel, Field
from dataclasses import dataclass

from spectrum.red.metrics import AdversarialMetrics


@dataclass
class Region:
    """Represents a vulnerable region in feature space."""
    center: List[float]
    radius: float
    sample_count: int


@dataclass
class Finding:
    """Represents a critical finding from the audit."""
    severity: Literal["CRITICAL", "HIGH", "MEDIUM", "LOW"]
    title: str
    description: str
    metric_name: str
    metric_value: float


@dataclass
class Recommendation:
    """Represents an actionable recommendation."""
    priority: Literal["CRITICAL", "HIGH", "MEDIUM", "LOW"]
    title: str
    description: str
    actions: List[str]


@dataclass
class RobustnessReport:
    """Detailed robustness assessment from adversarial testing."""
    # Empirical robustness
    empirical_robustness_l2: float      # Mean L2 perturbation for successful attacks
    empirical_robustness_linf: float    # Mean L∞ perturbation

    # Attack results
    attack_success_rate: float          # Fraction of samples successfully attacked
    min_perturbation: float             # Smallest successful perturbation (worst case)
    median_perturbation: float          # Typical perturbation required

    # Per-feature analysis
    feature_sensitivity: Dict[str, float]  # Which features are most vulnerable
    vulnerable_regions: List[Region]        # Clusters of high-vulnerability samples

    # Certified bounds (if applicable)
    clever_score: Optional[float] = None       # Certified lower bound

    # Metadata
    attack_type: str = "Unknown"
    samples_tested: int = 0
    queries_used: int = 0


@dataclass
class RegulatoryAssessment:
    """Assessment against a specific regulatory requirement."""
    regulation: str                     # "EU_AI_ACT_ART15", "CFPB", etc.
    requirement: str                    # Specific requirement being assessed

    metric_name: str                    # Which raw metric applies
    metric_value: float                 # The measured value
    threshold: float                    # Regulatory/industry threshold

    status: Literal["PASS", "MARGINAL", "FAIL"]
    confidence: float                   # Statistical confidence in assessment

    evidence: str                       # Plain-language explanation
    citation: str                       # Regulatory citation


@dataclass
class AuditSummary:
    """High-level audit summary with drill-down capabilities."""
    overall_risk: Literal["LOW", "MODERATE", "HIGH", "CRITICAL"]

    robustness_assessment: str          # "ROBUST", "MARGINAL", "FRAGILE"
    fairness_assessment: str            # "COMPLIANT", "MARGINAL", "NON_COMPLIANT"
    explainability_assessment: str      # "ADEQUATE", "PARTIAL", "INADEQUATE"

    critical_findings: List[Finding]    # RED findings requiring immediate attention
    recommendations: List[Recommendation]

    # Drill-down available
    detailed_robustness: Optional[RobustnessReport] = None
    regulatory_mappings: Optional[List[RegulatoryAssessment]] = None

class ComplianceReport(BaseModel):
    """
    Compliance report structure for audit artifacts.

    This model validates and structures the output of governance audits,
    ensuring all required fields are present for regulatory compliance.
    """

    # Model Information
    model_name: str = Field(..., description="Name of the model being audited")
    model_type: str = Field(..., description="Type of model (Tabular, LLM, etc.)")

    # Risk Assessment
    risk_level: str = Field(..., description="Risk level from RiskProfile (HIGH, MEDIUM, LOW)")
    confidence_required: float = Field(..., ge=0.0, le=1.0, description="Required confidence level (1 - alpha)")
    empirical_coverage: Optional[float] = Field(None, ge=0.0, le=1.0, description="Actual coverage achieved on test set")

    # Attack Results - Comprehensive Metrics
    adversarial_metrics: Dict = Field(..., description="Comprehensive adversarial testing metrics from spectrum.red")

    # Explainability
    sample_adverse_reasons: List[str] = Field(default_factory=list, description="Sample explanations for adverse predictions")

    # Drift Monitoring
    data_drift_status: str = Field(..., description="Status of data drift check")
    data_drift_alert: bool = Field(..., description="Whether drift alert was triggered")

    # Audit Metadata
    lineage_run_id: str = Field(..., description="OpenLineage run ID for traceability")
    audit_log_path: str = Field(..., description="Path to RCIA audit log file")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Timestamp of report generation")
    
    class Config:
        json_schema_extra = {
            "example": {
                "model_name": "RandomForestClassifier",
                "model_type": "Tabular",
                "risk_level": "HIGH",
                "confidence_required": 0.95,
                "empirical_coverage": 0.94,
                "adversarial_metrics": {
                    "attack_type": "HopSkipJump",
                    "attack_success_rate": 0.15,
                    "samples_tested": 100,
                    "samples_successful": 15,
                    "empirical_robustness_l2": 2.34,
                    "empirical_robustness_linf": 0.45,
                    "min_perturbation_l2": 0.12,
                    "max_perturbation_l2": 5.67,
                    "median_perturbation_l2": 2.10,
                    "queries_used": 100000,
                    "avg_queries_per_sample": 1000.0
                },
                "sample_adverse_reasons": ["Credit Score below threshold", "High debt-to-income ratio"],
                "data_drift_status": "✓ No Drift Detected",
                "data_drift_alert": False,
                "lineage_run_id": "3f9c2b4a-1234-5678-9abc-def012345678",
                "audit_log_path": "/var/log/rcia/audit.jsonl"
            }
        }